// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyauoSRWRQYSevKv4bXP8EmCb9mRCUGAE',
    appId: '1:366827763255:web:ea5058909732268d42b1b2',
    messagingSenderId: '366827763255',
    projectId: 'flutter-ai-playground-fe7b7',
    authDomain: 'flutter-ai-playground-fe7b7.firebaseapp.com',
    storageBucket: 'flutter-ai-playground-fe7b7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQIUFSRVqYsOXEC8fHkclag27KYnSFKGU',
    appId: '1:366827763255:android:5d9d4c954f9d3f9642b1b2',
    messagingSenderId: '366827763255',
    projectId: 'flutter-ai-playground-fe7b7',
    storageBucket: 'flutter-ai-playground-fe7b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8Mfbv9ixxmw_0lr5pFYFYVszwf6E0E6c',
    appId: '1:366827763255:ios:02cde1dad0114e1342b1b2',
    messagingSenderId: '366827763255',
    projectId: 'flutter-ai-playground-fe7b7',
    storageBucket: 'flutter-ai-playground-fe7b7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8Mfbv9ixxmw_0lr5pFYFYVszwf6E0E6c',
    appId: '1:366827763255:ios:02cde1dad0114e1342b1b2',
    messagingSenderId: '366827763255',
    projectId: 'flutter-ai-playground-fe7b7',
    storageBucket: 'flutter-ai-playground-fe7b7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyauoSRWRQYSevKv4bXP8EmCb9mRCUGAE',
    appId: '1:366827763255:web:dc8bff3f4efab34042b1b2',
    messagingSenderId: '366827763255',
    projectId: 'flutter-ai-playground-fe7b7',
    authDomain: 'flutter-ai-playground-fe7b7.firebaseapp.com',
    storageBucket: 'flutter-ai-playground-fe7b7.firebasestorage.app',
  );
}
